pipeline {
    agent any
    stages {
        stage('Checkout Repository') {
            steps {
                git url: "https://github.com/gabbyTI/currency-conversion-microservice.git", branch:'main'
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    dockerImage = docker.build("gabbyti/currency-conversion:${BUILD_NUMBER}", '-t gabbyti/currency-conversion:latest -f Dockerfile .')
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    withDockerRegistry([ credentialsId: "dockerHub", url: "" ]){
                        dockerImage.push()
                    }
                }
            }
        }
    }
}

////////////////////////////////////////////////////////

// pipeline {
//     agent any

//     stages {

//         stage('Checkout Repository') {
//             steps {
//                 git url: 'https://github.com/gabbyTI/currency-exchange-microservice.git', branch:'main'
//             }
//         }

//         stage('Build Docker Image') {
//             steps {
//                 script {
//                     dockerImage = docker.build("gabbyti/currency-exchange:${BUILD_NUMBER}", "-t gabbyti/currency-exchange:latest -f Dockerfile .")
//                 }
//             }
//         }

//         stage('Push Docker Image') {
//             steps {
//                 script {
//                     withDockerRegistry([ credentialsId: "dockerHub", url: "" ]){
//                         dockerImage.push()
//                     }
//                 }
//             }
//         }
//     }
// }

